### ISSUE TITLE
sandwich trade test fail

### ISSUE THREAD

**Issue by jrhea** [delvtech/hyperdrive#660]
[FAIL. Reason: <no data> Counterexample: calldata=0x021db0e7000000000000000000000000000000000000000000033b79045f3d5e995c1c6c000000000000000000000dfc21cff3c57c675a8cec4da8489dde760f7b51549300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[3907629452404090895866988 [3.907e24], 5232368895829812198328282203278271572969104075740307 [5.232e51], 0, 0]] test_sandwich_short_trade(uint256,uint256,uint256,uint256) (runs: 5081, μ: 8935895, ~: 8964409)

**Comment by jalextowle** [comment]
I went through each of these issues, and they couldn't be reproduced. All of the tests passed with these inputs, so I'm going to mark this as outdated since there have been a lot of fixes implemented since this issue was opened.
