### ISSUE TITLE
Timestretch Analysis

### ISSUE THREAD

**Issue by jrhea** [delvtech/hyperdrive#835]
With the DSR moving from 5% to 15%, we need to decide how to configure this yield source. We don't want to do anything cute like configure it to 5% and initialize it to 15%. 

1) factory would prevent this 
2) spearbit found an issue that leads to insolvency if this were to be allowed. a fix was applied, but we should still keep this in mind: https://github.com/spearbit-audits/review-element-february/issues/51

Things to consider:
1) how long do we expect the DSR to stay at 15%?  This will require a time stretch that allows for more slippage.
2) if the DSR were to move back down to 5%, how much would LPs lose?
3) how much volume could the pool support at a 15% slippage?
4) if the pool was configured with a time stretch of 5%, then the variable moves to 15% - would the pool support this? What would happen to available liquidity as the shorts that pushed the rate to 15% mature. In other words, lets plot idle liquidity and share adjustment
5) Re-run fuzz tests configured for 15%

**Comment by wakamex** [comment]
after some rigorous economic analysis I have determined the next sDai rate move will be lower
![image](https://github.com/delvtech/hyperdrive/assets/16990562/7d2e8ddd-91a7-4987-8205-9bf0bf4d44b5)

**Comment by wakamex** [comment]
`your_loss_as_a_percentage = Δrate * arb_trade_size / liquidity`

**Comment by wakamex** [comment]
checks out
![image](https://github.com/delvtech/hyperdrive/assets/16990562/facf24f2-7213-4b19-b258-d496a67b7f83)

formula
```
effective_interest_rate = 
arb_return = variable_rate - effective_interest_rate
lp_return = variable_rate - arb_return * arb_base_proceeds / lp_liquidity
```

**Comment by wakamex** [comment]
I suggest let's pinch off this issue with #s 1-2 and start a new issue with the remaining questions, along with some new ones like:
- is this a good yield source? how does it compare to uniswap?
@jrhea do you mean comparing sDai vs. Uniswap or LPing in an sDai Hyperdrive pool vs. Uniswap?

remaining for #2: summarize impact going of low initialization at 5% going to high rates vs. high initialization at 15% going to low rates

**Comment by jrhea** [comment]
Ask @jalextowle about the min share reserves for dai and steth and update @wakamex's rule of thumb analysis

**Comment by jalextowle** [comment]
The minimum share reserves is 10e18 for DAI and 1e15 for ETH

**Comment by wakamex** [comment]
Using those minimums works (10e18 for DAI and 1e15 for ETH), with the following recommendations:
time stretch of 5% works well for rates up to 15-20% even with low liquidity
time stretch of 10% works well for rates up to 40% even with low liquidity
time stretch of 20% works well for rates up to 80-100% even with low liquidity
I'd probably still want to re-run some analysis for some instances, but this should cover the majority of cases
