### ISSUE TITLE
Update `calculate_open_short` to be at parity with the contracts

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive#894]
Currently if you call [`calculate_open_short`](https://github.com/delvtech/hyperdrive/blob/main/crates/hyperdrive-math/src/short/open.rs#L31) you'll get back at smaller `traderDeposit` result than if you call `openShort` in view mode.

Fixing this would solve an issue in the UI when users need to set an allowance for the exact `traderDeposit` amount.

**Comment by wakamex** [comment]
I think this was closed in error.

We still don't have parity between SDK and contracts.

#869 says "Note: We have a ticket for making the sdk and contracts at parity with each other, at which point we can remove this 1% padding: https://github.com/delvtech/hyperdrive/issues/894".

So I think this TODO is still valid https://github.com/delvtech/hyperdrive-frontend//blob/95eebc064ef5161502ba89f8891a6c7af793e13e/apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx#L170
