### ISSUE TITLE
Testnet Smart Contract Deployment

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive#897]
1. [ ] Factory Deployment Script
    - Deploy contracts and transfer ownership to governance
    - Deploy registry administered by DELV
    - Deploy mock vaults for sDAI and stETH
2. [ ] Verify Smart Contracts on Etherscan
3. [ ] Factory Deploy to Sepolia
4. [ ] Pool Deploy to Sepolia
     - sDAI and stETH markets
         - 2 weeks and 1 month

5. [ ] Rate Configuration
      - [ ] Manual Updates for sDAI
      - [ ] Rate-Daddy for stETH

**Comment by jalextowle** [comment]
@CPSTL We're going to need the DAO address to deploy.

**Comment by CPSTL** [comment]
> [@CPSTL](https://github.com/CPSTL) We're going to need the DAO address to deploy.

0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b
