### ISSUE TITLE
Bug-bounty Updates

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive#932]
- [x] Disable Immunifi for Council (cc. @jrhea, @CPSTL, @jalextowle)
- [x] Consider switching to Cantina
- [ ] Review SOW from Cantina (cc. @jrhea, @smaroo, @CPSTL, @jalextowle)

**Comment by jalextowle** [comment]
We made a decision. We're going to lock it in, and we'll close this issue once it's signed.

**Comment by dpaiton** [comment]
Closing since this is marked as Done.
