### ISSUE TITLE
Move Council Bug Bounty to `security@delv.tech`

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive#975]
Create a `security@delv.tech` email and forward the emails to `jonny@delv.tech`, `ryan@delv.tech`, `matt@delv.tech`, and `alex@delv.tech`.

**Comment by smaroo** [comment]
security@delv.tech has been created with forwarding turned on!

**Comment by jalextowle** [comment]
We might need to do some comms associated with this (cc. @jalextowle)

**Comment by smaroo** [comment]
Looks like it's still up: https://immunefi.com/bug-bounty/delv/ | followed up with ImmuneFi on 5/15

**Comment by jrhea** [comment]
> Looks like it's still up: https://immunefi.com/bug-bounty/delv/ | followed up with ImmuneFi on 5/15

It should be down now
